---
- hosts: all
  become: yes

  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
        upgrade: safe
        autoclean: yes
        force_apt_get: yes
        cache_valid_time: 86400

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: true

    - name: Add the Wi-Fi password
      template:
        src: ~/temp/rasberry_pi/ansible/ubuntu_server_settings/ubuntu_pass.txt
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        mode: 0644
      register: wifi_pass

    - name: Apply netplan for eth0 and wi-fi
      command: netplan generate && netplan apply
      when: wifi_pass.changed
