---
- hosts: all
  become: yes
  gather_facts: yes
  # ad-hoc command to check ansible_facts
  # ansible -m setup all -i inventory.txt --ask-pass
  # ansible -i hosts all -m debug -a "var=hostvars['ansible_facts']" -i inventory.txt

  tasks:
    - name: Reboot to avoid process lock from initial boot
      reboot:
    - name: Update Cache
      apt:
        update_cache: yes
        upgrade: safe
        autoclean: yes
        force_apt_get: yes
        cache_valid_time: 86400
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: true
    - name: Add the Wi-Fi password
      template:
        src: ubuntu_pass.txt
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        mode: 0644
      register: wifi_pass
    - name: Apply netplan for eth0 and wi-fi
      command: netplan generate && netplan apply
      when: wifi_pass.changed
    - name: Wait for the task to complete, remove ethernet cable and find your Wi-Fi ip.
      reboot:
    - debug:
        msg: "Your Wi-Fi IP is {{ansible_wlan0.ipv4.address}}"
